### ISSUE TITLE
new Node

### ISSUE THREAD

**Issue by Gblur** [Gblur/capstone-project#2]
Title: Node Description
Value Proposition
- As a project creator
- I want to add a new node
- in order to extend the project data

Description

![Image](https://user-images.githubusercontent.com/25586795/227508809-4675f77f-9e55-4c4e-99ef-31b6f9cdff86.png)

Acceptance criteria
- [x] you should be able to make a connection between your previous and current node
- [x] there should be a default name for the newly created node and you should be able to change the node name  
- [x] each type should have its custom styles 
- [x] created nodes shall be visible after refresh
- [x] may be saved
 
Tasks
- [x] get an overview about built in library functions 
- [x] update nodes and edges
- [ ] write a onDragOut handler function to create a connection between the previous and the new node
- [x] save data array in db or elsewhere
- [ ] Write tests
- [x] Generate dummy-data

**Comment by liebeckm** [comment]
I really like this project! ⭐️
Was thinking about if this is a little too much for one user story? maxybe put color change or item counter into another one? also it is good to specify for what exactly you plan to write tests, so you don't forget anything later.

**Comment by Gblur** [comment]
the problem is that it always depends on the data youve changed. But maybe I can separate the color modification as a logic feature for every map type

**Comment by abieber1408** [comment]
Looks awesome!! 
Maybe you can hide it in some way.

**Comment by Kachev** [comment]
It looks great!
I noticed a small bug when you enter a note and want to choose whether it is an issue or a branch, but if you move the cursor outside the drop-down menu, the input field moves as well.
