### ISSUE TITLE
dashboard Create

### ISSUE THREAD

**Issue by Gblur** [Gblur/capstone-project#7]
Title: Node Description
Value Proposition
- As a project creator
- I want to create a new project
- in order to extend the project database

Description

![Image](https://user-images.githubusercontent.com/25586795/231121353-fd36ce61-883f-4237-8a07-8c32e85d108a.png)

Acceptance criteria
- [x] button for create should open a modal with a form
- [x] after submitting the form, the user shall be pushed to the predetermined slug
 
Tasks
- [x] create Dashboard component with a create Button
- [x] create Form

**Comment by rabe200** [comment]
this looks like a lot for one user story
- maybe split into different userstories:
- project list
- button to create
- form 
- etc
?

**Comment by toshydev** [comment]
That's a lot of features for one user story. You could split it into several user stories for `read` and `create` operations respectively.

**Comment by alexWaligorski** [comment]
Hi Florian, 
well done breaking down your user story! This seems much smaller and better definded.
- I would recommend being more specific on the form: Which inputs should it have?
- How will the dashboard look like? Do you already have such a component or do you need to create it fist? Then I'd also be a bit more specific about it
- Also: Please comsider adding text to your Button.. Your  wireframe shows a plus sign only, this might be a bit too vague about what can be added here

I hope this helps!
